using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace HangmanGame.EnumWords
{
    enum CarBrandWords
    {
        Acura,
        AlfaRomeo,
        AstonMartin,
        Audi,
        Bentley,
        BMW,
        Bugatti,
        Buick,
        Cadillac,
        Chevrolet,
        Chrysler,
        Citroen,
        Dacia,
        Datsun,
        Dodge,
        Ferrari,
        Fiat,
        Ford,
        GMC,
        GreatWall,
        Haval,
        Hennessey,
        Holden,
        Honda,
        Hummer,
        Hyundai,
        Infiniti,
        JAC,
        Jaguar,
        Jeep,
        Kia,
        Koenigsegg,
        Lada,
        Lamborghini,
        Lancia,
        LandRover,
        Lexus,
        Lincoln,
        Lotus,
        Maserati,
        Maybach,
        Mazda,
        McLaren,
        MercedesBenz,
        Mercury,
        MG,
        MINI,
        Mitsubishi,
        Morgan,
        Nissan,
        Noble,
        Oldsmobile,
        Opel,
        Pagani,
        Peugeot,
        Plymouth,
        Pontiac,
        Porsche,
        Ram,
        Renault,
        Rimac,
        RollsRoyce,
        Saab,
        Saturn,
        Scion,
        SEAT,
        Skoda,
        Smart,
        Subaru,
        Suzuki,
        Tesla,
        Toyota,
        Vauxhall,
        Volkswagen,
        Volvo,
        Wiesmann
    }
}
